apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-redis
  namespace: redis
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]

---


apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-redis-binding
  namespace: redis
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: cluster-config
roleRef:
  kind: Role
  name: secret-redis
  apiGroup: rbac.authorization.k8s.io
