apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flux-applier-namespace-binding
  namespace: test-app
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: test-app
roleRef:
  kind: ClusterRole
  name: namespace-patcher
  apiGroup: rbac.authorization.k8s.io
