  apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: serviceaccount-reader
  namespace: nginx
rules:
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["get", "list"]

--- 
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: serviceaccount-reader-binding
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: flux-applier
  namespace: cluster-config
roleRef:
  kind: Role
  name: serviceaccount-reader
  apiGroup: rbac.authorization.k8s.io
